#!/usr/bin/env bash
# Remove kleosrules-owned artifacts from ~/.cursor only.
# Preserves unknown hooks.json keys and foreign entries; restores backups.

owned_ok() {
  local rel="$1" dst="$2" want have
  want="$(awk -v k="$rel" '$1==k{print $2; exit}' "$HOME_C/kleosrules-owned.txt" 2>/dev/null || true)"
  have="$(owned_hash "$dst" 2>/dev/null || true)"
  if [[ -n "$want" && -n "$have" ]]; then
    [[ "$want" == "$have" ]]
    return $?
  fi
  cmp -s "$PACK/rules/$(basename "$rel")" "$dst" 2>/dev/null \
    || cmp -s "$PACK/agents/$(basename "$rel")" "$dst" 2>/dev/null
}

restore_bak() {
  local dst="$1"
  if [[ -f "$dst.pre-kleos-bak" ]]; then
    mv -f "$dst.pre-kleos-bak" "$dst"
    echo "[restore] $dst from pre-kleos backup"
  fi
}

# remove_owned REL: delete ~/.cursor/REL when this pack owns it, then restore
# the pre-install backup.
remove_owned() {
  local dst="$HOME_C/$1"
  [[ -f "$dst" ]] || return 0
  if owned_ok "$1" "$dst"; then
    rm -f "$dst"
    echo "[rm] ~/.cursor/$1"
    restore_bak "$dst"
  else
    echo "[keep] differing ~/.cursor/$1 (not owned)"
  fi
}

uninstall_home() {
  local name skill dst target a
  if [[ -f "$HOME_C/hooks.json" ]]; then
    strip_owned_hooks_json "$HOME_C/hooks.json"
  fi
  remove_owned_hook_files "$HOME_C/hooks"
  # Generated by git-bash-shim.ps1 on first run (compiled P/Invoke helper cache).
  if [[ -f "$HOME_C/hooks/KleosPipeUtil.dll" ]]; then
    rm -f "$HOME_C/hooks/KleosPipeUtil.dll"
    echo "[rm] ~/.cursor/hooks/KleosPipeUtil.dll (shim cache)"
  fi
  for name in "${GLOBAL[@]}" kleosr; do
    remove_owned "rules/${name}.mdc"
  done
  while IFS= read -r skill; do
    [[ -z "$skill" ]] && continue
    dst="$HOME_C/skills/$skill"
    if [[ -L "$dst" ]]; then
      target="$(readlink "$dst" 2>/dev/null || true)"
      if [[ "$target" == *"/kleosrules/"* || "$target" == "$PACK/skills/$skill" ]]; then
        rm -f "$dst"
        echo "[rm] ~/.cursor/skills/$skill (symlink)"
      fi
    elif [[ -d "$dst" ]] && [[ "${FORCE:-0}" == "1" ]]; then
      rm -rf "$dst"
      echo "[rm] ~/.cursor/skills/$skill (FORCE=1 directory copy)"
    fi
  done < <(manifest_list '.skills[], .retiredSkills[]' | sort -u)
  prune_skill_catalog_backups "$HOME_C/skills"
  while IFS= read -r a; do
    remove_owned "agents/${a}.md"
  done < <(manifest_list '.agents[]')
  rm -f "$HOME_C/kleosrules-owned.txt"
  echo "[done] kleosrules uninstall complete (if you ever pasted the charter into Cursor Settings → User Rules, remove it manually)"
}
